/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InputMinusPlus {
        "max": number;
        "min": number;
        "name": string;
    }
}
declare global {
    interface HTMLInputMinusPlusElement extends Components.InputMinusPlus, HTMLStencilElement {
    }
    var HTMLInputMinusPlusElement: {
        prototype: HTMLInputMinusPlusElement;
        new (): HTMLInputMinusPlusElement;
    };
    interface HTMLElementTagNameMap {
        "input-minus-plus": HTMLInputMinusPlusElement;
    }
}
declare namespace LocalJSX {
    interface InputMinusPlus {
        "max"?: number;
        "min"?: number;
        "name"?: string;
    }
    interface IntrinsicElements {
        "input-minus-plus": InputMinusPlus;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "input-minus-plus": LocalJSX.InputMinusPlus & JSXBase.HTMLAttributes<HTMLInputMinusPlusElement>;
        }
    }
}
